// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: msg.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg_Type int32

const (
	Msg_TYPE_UNSPECIFIED Msg_Type = 0
	Msg_TYPE_HELLO       Msg_Type = 1
	Msg_TYPE_HELLO_ACK   Msg_Type = 2
	Msg_TYPE_SEND        Msg_Type = 3
	Msg_TYPE_SEND_ACK    Msg_Type = 4
	Msg_TYPE_READ        Msg_Type = 5
	Msg_TYPE_READ_ACK    Msg_Type = 6
)

// Enum value maps for Msg_Type.
var (
	Msg_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_HELLO",
		2: "TYPE_HELLO_ACK",
		3: "TYPE_SEND",
		4: "TYPE_SEND_ACK",
		5: "TYPE_READ",
		6: "TYPE_READ_ACK",
	}
	Msg_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_HELLO":       1,
		"TYPE_HELLO_ACK":   2,
		"TYPE_SEND":        3,
		"TYPE_SEND_ACK":    4,
		"TYPE_READ":        5,
		"TYPE_READ_ACK":    6,
	}
)

func (x Msg_Type) Enum() *Msg_Type {
	p := new(Msg_Type)
	*p = x
	return p
}

func (x Msg_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Msg_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_proto_enumTypes[0].Descriptor()
}

func (Msg_Type) Type() protoreflect.EnumType {
	return &file_msg_proto_enumTypes[0]
}

func (x Msg_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Msg_Type.Descriptor instead.
func (Msg_Type) EnumDescriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0, 0}
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Msg_Type `protobuf:"varint,1,opt,name=type,proto3,enum=postie.v1.client.Msg_Type" json:"type,omitempty"`
	// Types that are assignable to Msg:
	//
	//	*Msg_Hello
	//	*Msg_HelloAck
	//	*Msg_Send
	//	*Msg_SendAck
	//	*Msg_Read
	//	*Msg_ReadAck
	Msg isMsg_Msg `protobuf_oneof:"msg"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetType() Msg_Type {
	if x != nil {
		return x.Type
	}
	return Msg_TYPE_UNSPECIFIED
}

func (m *Msg) GetMsg() isMsg_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *Msg) GetHello() *MsgHello {
	if x, ok := x.GetMsg().(*Msg_Hello); ok {
		return x.Hello
	}
	return nil
}

func (x *Msg) GetHelloAck() *MsgHelloAck {
	if x, ok := x.GetMsg().(*Msg_HelloAck); ok {
		return x.HelloAck
	}
	return nil
}

func (x *Msg) GetSend() *MsgSend {
	if x, ok := x.GetMsg().(*Msg_Send); ok {
		return x.Send
	}
	return nil
}

func (x *Msg) GetSendAck() *MsgSendAck {
	if x, ok := x.GetMsg().(*Msg_SendAck); ok {
		return x.SendAck
	}
	return nil
}

func (x *Msg) GetRead() *MsgRead {
	if x, ok := x.GetMsg().(*Msg_Read); ok {
		return x.Read
	}
	return nil
}

func (x *Msg) GetReadAck() *MsgReadAck {
	if x, ok := x.GetMsg().(*Msg_ReadAck); ok {
		return x.ReadAck
	}
	return nil
}

type isMsg_Msg interface {
	isMsg_Msg()
}

type Msg_Hello struct {
	Hello *MsgHello `protobuf:"bytes,2,opt,name=hello,proto3,oneof"`
}

type Msg_HelloAck struct {
	HelloAck *MsgHelloAck `protobuf:"bytes,3,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type Msg_Send struct {
	Send *MsgSend `protobuf:"bytes,4,opt,name=send,proto3,oneof"`
}

type Msg_SendAck struct {
	SendAck *MsgSendAck `protobuf:"bytes,5,opt,name=send_ack,json=sendAck,proto3,oneof"`
}

type Msg_Read struct {
	Read *MsgRead `protobuf:"bytes,6,opt,name=read,proto3,oneof"`
}

type Msg_ReadAck struct {
	ReadAck *MsgReadAck `protobuf:"bytes,7,opt,name=read_ack,json=readAck,proto3,oneof"`
}

func (*Msg_Hello) isMsg_Msg() {}

func (*Msg_HelloAck) isMsg_Msg() {}

func (*Msg_Send) isMsg_Msg() {}

func (*Msg_SendAck) isMsg_Msg() {}

func (*Msg_Read) isMsg_Msg() {}

func (*Msg_ReadAck) isMsg_Msg() {}

type MsgHello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgHello) Reset() {
	*x = MsgHello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgHello) ProtoMessage() {}

func (x *MsgHello) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgHello.ProtoReflect.Descriptor instead.
func (*MsgHello) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

type MsgHelloAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgHelloAck) Reset() {
	*x = MsgHelloAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgHelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgHelloAck) ProtoMessage() {}

func (x *MsgHelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgHelloAck.ProtoReflect.Descriptor instead.
func (*MsgHelloAck) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{2}
}

type MsgSend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data     []byte            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metadata map[string][]byte `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MsgSend) Reset() {
	*x = MsgSend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSend) ProtoMessage() {}

func (x *MsgSend) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSend.ProtoReflect.Descriptor instead.
func (*MsgSend) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{3}
}

func (x *MsgSend) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MsgSend) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MsgSendAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *MsgSendAck) Reset() {
	*x = MsgSendAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSendAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSendAck) ProtoMessage() {}

func (x *MsgSendAck) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSendAck.ProtoReflect.Descriptor instead.
func (*MsgSendAck) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{4}
}

func (x *MsgSendAck) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type MsgRead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgRead) Reset() {
	*x = MsgRead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRead) ProtoMessage() {}

func (x *MsgRead) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRead.ProtoReflect.Descriptor instead.
func (*MsgRead) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{5}
}

type MsgReadAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgReadAck) Reset() {
	*x = MsgReadAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgReadAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgReadAck) ProtoMessage() {}

func (x *MsgReadAck) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgReadAck.ProtoReflect.Descriptor instead.
func (*MsgReadAck) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{6}
}

var File_msg_proto protoreflect.FileDescriptor

var file_msg_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x6f, 0x73,
	0x74, 0x69, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x8d, 0x04,
	0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x48, 0x00, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x3c, 0x0a, 0x09, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70,
	0x6f, 0x73, 0x74, 0x69, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e,
	0x4d, 0x73, 0x67, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x08, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x41, 0x63, 0x6b, 0x12, 0x2f, 0x0a, 0x04, 0x73, 0x65, 0x6e, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x6e, 0x64,
	0x48, 0x00, 0x52, 0x04, 0x73, 0x65, 0x6e, 0x64, 0x12, 0x39, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64,
	0x5f, 0x61, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6f, 0x73,
	0x74, 0x69, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x73,
	0x67, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x07, 0x73, 0x65, 0x6e, 0x64,
	0x41, 0x63, 0x6b, 0x12, 0x2f, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x61, 0x64, 0x48, 0x00, 0x52, 0x04,
	0x72, 0x65, 0x61, 0x64, 0x12, 0x39, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x61, 0x63, 0x6b,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x61,
	0x64, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x61, 0x64, 0x41, 0x63, 0x6b, 0x22,
	0x84, 0x01, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x48, 0x45, 0x4c, 0x4c, 0x4f, 0x10, 0x01, 0x12, 0x12,
	0x0a, 0x0e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x48, 0x45, 0x4c, 0x4c, 0x4f, 0x5f, 0x41, 0x43, 0x4b,
	0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x45, 0x4e, 0x44, 0x10,
	0x03, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x41,
	0x43, 0x4b, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x41,
	0x44, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44,
	0x5f, 0x41, 0x43, 0x4b, 0x10, 0x06, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x0a, 0x0a,
	0x08, 0x4d, 0x73, 0x67, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x4d, 0x73, 0x67,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x41, 0x63, 0x6b, 0x22, 0x9f, 0x01, 0x0a, 0x07, 0x4d, 0x73, 0x67,
	0x53, 0x65, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x43, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x6f, 0x73,
	0x74, 0x69, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x73,
	0x67, 0x53, 0x65, 0x6e, 0x64, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x3b, 0x0a,
	0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x20, 0x0a, 0x0a, 0x4d, 0x73,
	0x67, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x09, 0x0a, 0x07,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x61, 0x64, 0x22, 0x0c, 0x0a, 0x0a, 0x4d, 0x73, 0x67, 0x52, 0x65,
	0x61, 0x64, 0x41, 0x63, 0x6b, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x65, 0x2d, 0x6c, 0x61, 0x62, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x65, 0x2f, 0x76, 0x31, 0x2f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData = file_msg_proto_rawDesc
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_proto_rawDescData)
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_msg_proto_goTypes = []interface{}{
	(Msg_Type)(0),       // 0: postie.v1.client.Msg.Type
	(*Msg)(nil),         // 1: postie.v1.client.Msg
	(*MsgHello)(nil),    // 2: postie.v1.client.MsgHello
	(*MsgHelloAck)(nil), // 3: postie.v1.client.MsgHelloAck
	(*MsgSend)(nil),     // 4: postie.v1.client.MsgSend
	(*MsgSendAck)(nil),  // 5: postie.v1.client.MsgSendAck
	(*MsgRead)(nil),     // 6: postie.v1.client.MsgRead
	(*MsgReadAck)(nil),  // 7: postie.v1.client.MsgReadAck
	nil,                 // 8: postie.v1.client.MsgSend.MetadataEntry
}
var file_msg_proto_depIdxs = []int32{
	0, // 0: postie.v1.client.Msg.type:type_name -> postie.v1.client.Msg.Type
	2, // 1: postie.v1.client.Msg.hello:type_name -> postie.v1.client.MsgHello
	3, // 2: postie.v1.client.Msg.hello_ack:type_name -> postie.v1.client.MsgHelloAck
	4, // 3: postie.v1.client.Msg.send:type_name -> postie.v1.client.MsgSend
	5, // 4: postie.v1.client.Msg.send_ack:type_name -> postie.v1.client.MsgSendAck
	6, // 5: postie.v1.client.Msg.read:type_name -> postie.v1.client.MsgRead
	7, // 6: postie.v1.client.Msg.read_ack:type_name -> postie.v1.client.MsgReadAck
	8, // 7: postie.v1.client.MsgSend.metadata:type_name -> postie.v1.client.MsgSend.MetadataEntry
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgHello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgHelloAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSendAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgRead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgReadAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_msg_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Msg_Hello)(nil),
		(*Msg_HelloAck)(nil),
		(*Msg_Send)(nil),
		(*Msg_SendAck)(nil),
		(*Msg_Read)(nil),
		(*Msg_ReadAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		EnumInfos:         file_msg_proto_enumTypes,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_rawDesc = nil
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
